### ISSUE TITLE
MirthWebServer hardcodes Keystore type used for SSLConnector

### ISSUE THREAD

**Issue by ab-20-m** [nextgenhealthcare/connect#4443] opened 2021-01-07 13:51 UTC
MirthWebServer hardcodes the Keystore type to JCEKS when setting up the SSLConnector. This behavior will be a blocker to implement #3960. BCFIPS only supports BCFKS and PKCS12. In FIPS approved mode, BCFIPS only allows BCFKS.

**Comment by pladesma** [comment] 2021-04-02 17:50
Closing as duplicate of #4099.

**Closed as completed by pladesma** 2021-04-02 17:50 UTC
Labels: duplicate, triaged
