### ISSUE TITLE
Administrator Launcher does not work if we define a http context path

### ISSUE THREAD

**Issue by adreyfus** [nextgenhealthcare/connect#5] opened 2019-01-29 08:38 UTC
Hi ! Thank you for this impressive work. Unfortunately there is a bug in the administrator launcher (v1.0.0).

If the variable `http.contextpath` (in `mirth.properties`) is defined other than root, the administrator launcher fails to connect with the error `"Unable to retrieve payload from HTTP request. URI: https://10.33.25.176:9443/webstart"`.

As can be seen in this message,  the context does not appear. So it seems that one step of the connection attempt removes it.

**Comment by narupley** [comment] 2019-01-29 17:44
Created an issue for this: [MIRTH-4380](http://www.mirthcorp.com/community/issues/browse/MIRTH-4380)

**Comment by adreyfus** [comment] 2019-01-30 08:04
Thanks ! :)

**Comment by davutg** [comment] 2020-01-09 15:32
**Trust anchor for certification path not found.** 

Even for https://localhost:8443 for current 3.9.0 dev branch with Admin Launcher 1.1.0.

-JDK 1.8 update 20
-Site address is added in Control Panel Java secure sites and security option High selected. 
-SSL is added to Trusted Root Authorities (confirmed after registering to physical registry). 

After uninstalling administrative console I'm able to start MirthUI thru JNLP. 

I'm not able to figure out exactly since I don't have access to Admin Launcher but it appeared to me mirthconnect alias certificate is not signed from CA Auths and Admin Launcher is trying to validate it but it fails on its own Trust Manager for some reason. Maybe it's SSLContext is different.

**Comment by cturczynskyj** [comment] 2020-04-29 22:44
@davutg Your issue doesn't seem related to this but I'll comment here before closing this issue. It sounds like you are building Connect on your own, self signing the jars, and using the Admin Launcher to load the Connect Client. The Admin Launcher is built with your security in mind and to ensure the jars are signed properly by a known good entity. If you are indeed building Connect on your own then you should sign your jars with one of the "official" Java JCE code signing CA certs (CN=JCE Code Signing CA).

The other option, though it is only recommended for use while developing and not in production, is to launch the Admin Launcher with the `-k` option which:

> "Allows JARs signed with self-signed certificates to be verified. This should only be used for development/testing purposes."

If these assumptions aren't correct then I suggest you open a new issue that is specific to the problem you are experiencing.

**Comment by cturczynskyj** [comment] 2020-04-29 22:45
Closing, issue is fixed in Admin Launcher 1.1.0 release.

**Closed as completed by cturczynskyj** 2020-04-29 22:45 UTC

**Comment by davutg** [comment] 2020-04-29 23:17
@cturczynskyj  Thanks , really appreciated your explanation. I compile myself, because I coded https SSL certificate support and UDP support kind of things in addition to this open source edition. Yes, our certificate is self signed and I don't know how to let admin launcher to let it work. It's also okay without launcher for us, but happy to see that this issue is resolved.
