### ISSUE TITLE
Admin launcher does not persist or store previously accepted certificates for client plugins

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4275] opened 2020-05-11 21:30 UTC
The Launcher does not persist approvals for certificates. Traditional JavaWS has the option to permanently trust the certificate so should the Launcher.

Repro steps:
1. Start the Launcher
2. Launch an MC instance which has a self-signed client library
3. Get the yes/no prompt to accept the certificate
4. Quit MC 
5. Quit the Launcher
6. Repeat steps 1 and 2
7. You'll be prompted again

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4399
Reporter: jbartels
Created: 2019-03-28T11:11:46.000-0700

**Comment by rbeckman-nextgen** [comment] 2020-05-11 21:30
Fixing this issue may be a workaround for MIRTH-4367 in that if the certificate acceptance persists a user would only run into the dialog once and thus reduce their exposure to the crashing behavior when that dialog is shown.

Imported Comment. Original Details:
Author: jbartels
Created: 2019-03-28T11:13:12.000-0700

**Comment by jonbartels** [comment] 2021-03-26 19:00
This case would be wholly addressed by the changes proposed at https://github.com/nextgenhealthcare/connect/issues/4379

**Comment by cturczynskyj** [comment] 2021-03-26 22:30
Closing as duplicate of #4379

**Closed as completed by cturczynskyj** 2021-03-26 22:30 UTC
Labels: duplicate, triaged
