### ISSUE TITLE
User Authorization Plugin, annoying error message on login.

### ISSUE THREAD

**Issue by is-simon** [nextgenhealthcare/connect#4465] opened 2021-02-26 19:26 UTC
A user MUST have to right to view the resource and tags settings, orelse an error message dialog is shown on startup (administrator). It is quite annoying.

This is the faulty line for the resources:
https://github.com/nextgenhealthcare/connect/blob/a8e3768f63660c7a3e4301236e43dadb635ab006/client/src/com/mirth/connect/client/ui/SettingsPanelResources.java#L128

And here for the tags:
https://github.com/nextgenhealthcare/connect/blob/a8e3768f63660c7a3e4301236e43dadb635ab006/client/src/com/mirth/connect/client/ui/tag/SettingsPanelTags.java#L146

Not sure how this could be resolved, but I think the `alertThrowable` function needs to be called with the `showMessageOnForbidden` set to `false`.

**Comment by cturczynskyj** [comment] 2021-02-27 00:13
First, next time, please use one of the issue templates as this really helps us understand your environment (For example, on what version of Connect are you observing this?). Second, this sounds like something that only occurs when using the User Auth commercial extension and the best place to report issues or ideas regarding commercial extensions is through the NextGen Success Community.

In addition, testing locally, we are unable to reproduce this. We've created a user and reduced the resource and tags permissions by removing the "view" permission and saw no errors. We also reduced those permissions by removing all of the permissions for the resource and tags and still saw no errors.

I'm going to close this here and please open a ticket in the Success Community with some more details (screenshots, logs, Connect version, etc.) on the behavior you are experiencing.

**Closed as completed by cturczynskyj** 2021-02-27 00:13 UTC
Labels: triaged
