### ISSUE TITLE
May I ask when Chinese operations can be supported

### ISSUE THREAD

**Issue by ourlang** [nextgenhealthcare/connect#5868] opened 2023-08-02 14:50 UTC
May I ask when Chinese operations can be supported

**Comment by pacmano1** [comment] 2023-08-02 14:57
Do you mean "When will Mirth be avaiable in other languages"?   Or do you have character set problems with the existing version of Mirth?

The term "Chinese operations" does not seem to be a good translation.

Also, are you asking for this? https://github.com/nextgenhealthcare/connect/issues/5570

**Comment by pladesma** [comment] 2023-10-18 19:37
Fully supporting chinese characters in the UI isn't currently on the roadmap, but it may be considered in the future. I'm closing this issue because it is a duplicate of existing issues including the one linked above and #4537.

**Closed as completed by pladesma** 2023-10-18 19:37 UTC
Labels: documentation
