### ISSUE TITLE
[BUG] /webstart endpoint: Response header name 'X-Content-Type-Options?' contains invalid characters

### ISSUE THREAD

**Issue by fridlik** [nextgenhealthcare/connect#4464] opened 2021-02-26 12:00 UTC
**Describe the bug**
When trying to connect to Mirth through Apache proxy, I've got some errors due to the unsupported characters in HTTP header:
```
Response header name 'X-Content-Type-Options?' contains invalid characters, aborting request`
```

**To Reproduce**
```Bash
# curl localhost:8080/webstart -i -s
HTTP/1.1 200 OK
Date: Fri, 26 Feb 2021 11:56:57 GMT
Last-Modified: Fri, 26 Feb 2021 11:56:57 GMT
Content-Type: application/x-java-jnlp-file;charset=utf-8
Pragma: no-cache
X-Content-Type-Options?: nosniff
Content-Disposition: attachment; filename = "webstart.jnlp"
Transfer-Encoding: chunked
Server: Jetty(9.4.21.v20190926)
...
```

**Expected behavior**
Header `X-Content-Type-Options` does not contain question mark.

**Environment (please complete the following information):**
 - OS: Centos 7
 - Java 8
 - Connect Version 3.10.1

**Comment by MichaelLeeHobbs** [comment] 2021-03-23 14:27
Dup #4432 #4462

**Comment by cturczynskyj** [comment] 2021-03-23 22:30
Closing duplicate of #4432

**Closed as completed by cturczynskyj** 2021-03-23 22:30 UTC
Labels: bug, duplicate, triaged
