### ISSUE TITLE
Simple channel won't save

### ISSUE THREAD

**Issue by rrootdawg** [nextgenhealthcare/connect#4454] opened 2021-02-01 22:01 UTC
New to Mirth. I'm doing a simple xml to text conversion using a simple java source transformer and can't get it to save due to the below. Any idea on what might be causing this? java source transformer code is below the save errors. Mirth connect version is 3.3.0.7801.

com.mirth.connect.client.core.ClientException: method failed: HTTP/1.1 500 Java heap space
com.mirth.connect.client.core.ServerConnection.executePostMethod(ServerConnection.java:140)
com.mirth.connect.client.core.Client.updateChannel(Client.java:262)
com.mirth.connect.client.ui.Frame.updateChannel(Frame.java:1446)
com.mirth.connect.client.ui.ChannelSetup.saveChanges(ChannelSetup.java:1289)
com.mirth.connect.client.ui.Frame.confirmLeave(Frame.java:1394)
com.mirth.connect.client.ui.Frame.doShowChannel(Frame.java:1827)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
sun.reflect.misc.Trampoline.invoke(Unknown Source)
sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
sun.reflect.misc.MethodUtil.invoke(Unknown Source)
java.beans.EventHandler.invokeInternal(Unknown Source)
java.beans.EventHandler.access$000(Unknown Source)
java.beans.EventHandler$1.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.beans.EventHandler.invoke(Unknown Source)
com.sun.proxy.$Proxy9.actionPerformed(Unknown Source)
org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
org.jdesktop.swingx.JXHyperlink.fireActionPerformed(JXHyperlink.java:264)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

Here's the xml to text java:
var i;
var file="";
var delimiter="————————————-";
for(i=0;i<msg['Facility'].length();i++)
{
file+="Prov: "+msg['Facility'][i]['@Name'].toString()+"\n";
file+="CodeType: "+msg['Facility']['Charge'][i]['@Type'].toString()+"\n";
file+="Code: "+msg['Facility']['Charge']['Item'][i]['@Code'].toString()+"\n";
file+="Description: "+msg['Facility']['Charge']['Item'][i]['Descr'].toString()+"\n";
file+="Charge: "+msg['Facility']['Charge']['Item'][i]['Contracts']['Contract'][i]['@Charge'].toString()+"\n";
file+="Payer: "+msg['Facility']['Charge']['Item'][i]['Contracts']['Contract'][i]['@Payer'].toString()+"\n";
file+=delimiter+"\n";
}
channelMap.put("FILE",file);

**Comment by jonbartels** [comment] 2021-02-10 14:16
This is a client side memory error. How much memory are you giving the MC client when you start it?

If you are using the launcher this is a dropdown option in the launcher.
If you are using traditional webstart it is either a flag to `javaws` or an option in the JNLP file.

**Comment by rrootdawg** [comment] 2021-02-10 14:32
Thanks Jon.

I’ll explore this.

I deleted and rebuilt the channel and it worked. I think I just had a lot of “garbage” in the channel and this caused the memory error. I.E. dropping in large example files into the transformer viewer pane.



Robert Root
AVP, Provider Experience
803-264-9129 (w) | Ext. 49129 | 843-615-2833 (c)
BlueCross BlueShield of South Carolina<http://www.southcarolinablues.com/>
robert.root@bcbssc.com<mailto:robert.root@bcbssc.com> | CONFIDENTIALITY NOTICE<http://www.bcbssc.com/confidentiality.htm>

**Comment by jonbartels** [comment] 2021-02-10 15:00
> I think I just had a lot of “garbage” in the channel and this caused the memory error. I.E. dropping in large example files into the transformer viewer pane.

Yes that will directly cause the error you have. MC will parse those messages into its internal XML representation. In-memory XML is a HUGE memory hog.

If the issue is solved, close this ticket. If it carries on post any errors or logs you have and the open-source community can help.

**Closed as completed** 2021-02-10 15:08 UTC
