### ISSUE TITLE
[BUG] Channel clone doesn't include dependencies to the existint libraries

### ISSUE THREAD

**Issue by ppazos** [nextgenhealthcare/connect#5284] opened 2022-07-13 22:02 UTC
**Describe the bug**

Same as title.

**To Reproduce**

Start Mirth Server 4.0.1
Start Mirth Connect administrator from launcher, connecting to the server

1. Create a channel X
2. Create a library in code templates
3. Define the dependency from the channel X to the library
4. Clone the channel into channel Y
5. Check dependencies in channel Y and that is empty

So when running channel Y "as is" it will fail when one function from the code library is invoked.

**Expected behavior**

The cloned channel should be a carbon copy of the original channel, that is why it's a `clone`. Including libraries and scripts.

**Actual behavior**

Cloned channel doesn't include the dependencies to the code template libraries the original channel had.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Linux (CentOS), Windows 10, MacOS]
 - Java Distribution/Version [e.g. OpenJDK 11, Java 8 (201)]
 - Connect Version [e.g. 3.8.0]

**Workaround(s)**
Are there one or more workarounds for this issue currently?

**Additional context**

**Comment by pacmano1** [comment] 2022-07-13 22:36
Duplicate of https://github.com/nextgenhealthcare/connect/issues/4073

**Comment by pladesma** [comment] 2022-07-15 20:31
Closing as duplicate.

**Closed as completed by pladesma** 2022-07-15 20:31 UTC
Labels: bug, duplicate
