### ISSUE TITLE
Allow Administrator font size to be configurable

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3251] opened 2020-05-11 20:34 UTC
Since some of the UI depends on things being a specific size (like table rows), some work would have to be done to ensure that such components dynamically adjust for a variable font size.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3349
Reporter: narupley
Created: 2014-06-20T07:33:25.000-0700

**Comment by rbeckman-nextgen** [comment] 2020-05-11 20:34
Alternately, update the Administrator UI to respond to windows DPI scaling so the OS scaling factor is correctly applied to the application.

Imported Comment. Original Details:
Author: ted
Created: 2016-10-27T09:16:15.000-0700

**Comment by rbeckman-nextgen** [comment] 2020-05-11 20:34
With user moving to larger screens and higher resolutions, changing font size would be ideal. Font is eyes straining on a 40+ inch monitor that has 4k

Imported Comment. Original Details:
Author: kab7715
Created: 2017-11-16T16:25:42.000-0800

**Comment by rbeckman-nextgen** [comment] 2020-05-11 20:34
Either my eyes are noticeably worse than yesterday, or some java setting has made my font even smaller than normal. 

Imported Comment. Original Details:
Author: brettgrantham
Created: 2018-05-01T08:53:59.000-0700

**Comment by rbeckman-nextgen** [comment] 2020-05-11 20:34
I throw my hat in this ring. On Linux "Windows Compatibility" is not an option and on a high res DPI it's near impossible to read the information on the screen. I'm currently looking for a work around, if anyone has any leads on this that would be awesome!

Imported Comment. Original Details:
Author: bassicallychris
Created: 2019-10-11T09:20:44.000-0700

**Comment by koratech** [comment] 2020-05-21 23:59
The fonts on the UI seem to get smaller and smaller with new updates. I'm straining my eyes and the prblems seems not to be having a solution.

**Comment by gaensler** [comment] 2020-07-03 09:06
I think with High DPI Monitors getting more widely used in the last years this topic should get more attention.

**Comment by danihodovic** [comment] 2021-10-21 12:17
Is there any known workaround for running the Mirth Connect admin on a 4k display in Linux?

**Comment by cturczynskyj** [comment] 2021-10-26 23:48
> Is there any known workaround for running the Mirth Connect admin on a 4k display in Linux?

I had a little time to tinker with this and here are my findings on Ubuntu

1. Install openjdk11 (openjdk 9 and above support scaling)
2. Set GDK_SCALE for your terminal session or globally, to some integer larger than 1 `export GDK_SCALE=2`
3. Launch the Administrator Launcher from the terminal where you've exported the GDK_SCALE environment variable. Navigate to wherever it's installed (for me it was `/usr/local/mirth-administrator-launcher`) and start `./launcher`
4. Set "Java home" setting for the server you are going to launch Administrator from to "Custom" and supply where you have your openjdk installed. For me it was `/usr/lib/jvm/java-11-openjdk-amd64`
5. Click "Launch" and you should see the Administrator Launcher start in the scale supplied to GDK_SCALE.
![1x Scale](https://user-images.githubusercontent.com/15792647/138976708-a1b0ae17-1f48-4819-8375-8265478d5834.png)
![2x Scale](https://user-images.githubusercontent.com/15792647/138976754-61ff1eef-ce7b-4693-bac2-c34af6394591.png)

**Comment by danihodovic** [comment] 2021-10-27 09:17
Thanks @cturczynskyj !

**Comment by gaensler** [comment] 2021-11-02 15:41
That also works for me, but apparently only for Integer / whole number factors (2, 3, 4 etc.), but no float / fractional factors (1.2, 1.5 etc.). This seems to be general Java / Swing problem, see https://wiki.archlinux.org/title/HiDPI#Java_applications

If you want to set GDK_SCALE value only for mirth administrator without launching it manually from your terminal, you could tweak the Exec-part of your .desktop-file as follows
`Exec=env GDK_SCALE=2 /bin/sh "/opt/mirth-administrator-launcher/launcher"`
Maybe change the path to wherever your launcher lies on your local machine.

Another Tip: If you hover over the "Bundled" or "Default" Setting for Java Home in Administrator Launcher, a tooltip shows the recognized java version.

**Comment by tonygermano** [comment] 2021-11-04 16:24
@cturczynskyj I think this issue can be closed as a duplicate of #4780 since it looks like you guys already have an internal ticket linked to that one.

The information in this issue for enabling scaling in linux would be useful some other place where it's easier to find, perhaps in the wiki.

You can actually see the issues in your screenshots with using non-free Tahoma as the hard-coded font (which is pre-installed on Windows and Mac, but not Linux.) In the left menu bar you can see `About Mirth Con...` being cut off. Also the timestamp is truncated in the Last Deployed column. Neither of those UI elements are resizable.

**Comment by cturczynskyj** [comment] 2021-11-05 20:56
We were leaving the two open because we were hoping the focus with this issue would be scaling the Administrator without internal development work being necessary.

**Comment by pladesma** [comment] 2022-09-26 21:25
For the sake of completion, if you're using Windows, you can do the following to allow better scaling of the Mirth Connect UI:

1. Ensure you're using Java 9 or greater.
2. Navigate to your Java bin folder.
3. Right-click on `java.exe` and edit properties.
4. Go to the `Compatibility` tab and click `Change high DPI settings`.
5. Check the box next to `Override high DPI scaling behavior` and select `System` in the drop-down menu.
6. Open the Mirth Connect Administrator Launcher. 
7. For `Java Home`, select `Custom` and enter the path to your Java installation folder.
8. Launch the Mirth Connect Administrator.

Also, see this forum post for another solution https://forums.mirthproject.io/forum/mirth-connect/support/15397-mirth-and-4k-monitors#post100598.

Currently, we haven't found a good solution for Mac OS.

**Closed as completed by pladesma** 2022-09-26 21:25 UTC
