### ISSUE TITLE
[BUG] Connector properties nested changes are not detected

### ISSUE THREAD

**Issue by davutg** [nextgenhealthcare/connect#4989] opened 2022-01-28 08:29 UTC
**Describe the bug**
A clear and concise description of what the bug is. Is this consistently reproducible?

**To Reproduce**
Setup steps (if required). Example:
i.e. TransmissionModeProperties class has FrameModeProperties field, it's also a class. If any property of this nested class changed it's not being detected with simple use of `EqualsBuilder.reflectionEquals` in the current NextgenConnect.

A sample connector I've developed recently and encountered this issue. In below branch for TCP Connector there's IsTLS Enabled and send Auto ACK checks. Even these checks are part of the connector properties (nested), the change is not saved, and not appear as revision change.
https://github.com/CSCONNECT/connect/commits/development 

**Expected behavior**
All nested serializable properties need to be considered as change and cause revision change.  `EqualsBuilder.reflectionEquals` has an an overridden method to support this now.

**Actual behavior**
Only direct property of the connector is detected as a change but not nested props.

**Environment (please complete the following information):**
 - Windows 10, JDK8

**Workaround(s)**
As workaround any other simple direct property of connector can be changed and channel saved to enforce revision change.

**Additional context**
A property can be introduced FrameModeProperties  and only changing it in the screen will not work. I believe nested checking is a better approach and it can reduce checking deep property changes in the code. 

Related to #4950 @pladesma based on your request I created this issue.

**Comment by cturczynskyj** [comment] 2022-01-28 22:25
So it sounds like you are developing your own connector(s) maybe based on some in the open source Connect project. Could you include an example channel exported as XML? Could you also include the steps to reproduce the issue, like are you using the API, or the Connect Administrator? Thanks!

**Comment by cturczynskyj** [comment] 2022-02-10 23:01
Circling back to this after spending a bit more time looking over your code change. If we were to include your change, then it could alter some behavior where we override the `equals` method. Instead it may be better to just remove the `equals` method in `FrameModeProperties` and change the `equals` method in `TransmissionModeProperties` to call `EqualsBuilder.reflectionEquals`. This is untested, but if it works how I think it does it will be less of a breaking change.

**Comment by davutg** [comment] 2022-02-16 18:56
Agree, maybe writing some unit tests/UAT can help to ensure if this cause another issue or not.  There's a discussion about this new overloaded method here,
https://stackoverflow.com/a/9633089/413032
This new option might help getting rid of some equals.

**Comment by cturczynskyj** [comment] 2022-03-11 22:18
Closing since it seems like this is a very specific case for a 3rd party connector and the pull request has also been closed.

**Closed as completed by cturczynskyj** 2022-03-11 22:18 UTC
Labels: bug

**Comment by davutg** [comment] 2022-03-13 09:54
In my test I found a glitch. I'll fix and update my pull request. I'll also update you after using this change in production some time.
